version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: streamlit_app
    ports:
      - '8501:8501'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=mydatabase
      - DATABASE_URL=mysql+pymysql://root:rootpassword@db:3306/mydatabase
    volumes:
      - .:/app
      - /app/__pycache__
      - ./models/default_model.joblib:/app/models/default_model.joblib:ro

    depends_on:
      - db

volumes:
  db_data:

    